
Lmod is automatically replacing "gcc/11.3.0" with
"intel-oneapi-compilers/2023.1.0".

[2024-01-17 16:29:53,095] torch.distributed.run: [WARNING] 
[2024-01-17 16:29:53,095] torch.distributed.run: [WARNING] *****************************************
[2024-01-17 16:29:53,095] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-01-17 16:29:53,095] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "/scratch/elec/morphogen/morphological-llm-test-set/llm-examples/batch-inference-llama2/batch_inference.py", line 97, in <module>
    fire.Fire(main)
  File "/home/moisioa3/.conda/envs/llamamodule/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/moisioa3/.conda/envs/llamamodule/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/moisioa3/.conda/envs/llamamodule/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/scratch/elec/morphogen/morphological-llm-test-set/llm-examples/batch-inference-llama2/batch_inference.py", line 51, in main
    torch.cuda.set_device(local_rank)
  File "/home/moisioa3/.conda/envs/llamamodule/lib/python3.10/site-packages/torch/cuda/__init__.py", line 404, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2024-01-17 16:29:58,106] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1710 closing signal SIGTERM
[2024-01-17 16:29:58,370] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 1711) of binary: /home/moisioa3/.conda/envs/llamamodule/bin/python
Traceback (most recent call last):
  File "/home/moisioa3/.conda/envs/llamamodule/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/moisioa3/.conda/envs/llamamodule/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/moisioa3/.conda/envs/llamamodule/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/moisioa3/.conda/envs/llamamodule/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/moisioa3/.conda/envs/llamamodule/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/moisioa3/.conda/envs/llamamodule/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/scratch/elec/morphogen/morphological-llm-test-set/llm-examples/batch-inference-llama2/batch_inference.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-17_16:29:58
  host      : dgx3.int.triton.aalto.fi
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1711)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
